# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'wahaniya-corp(24cb7a23-a4cf-40e1-a530-af25a0a1060d)'
    KeyVaultName: 'kv-azurepipeline-sample'
    SecretsFilter: '*'

- script: |
    echo $key1 | base64
    echo $sample | base64
    echo $key2 | base64
    echo "base64 encoded?"
    echo $base64 | base64 -d
  env:
    key1: $(key1)
    sample: $(sample-key)
    key2: $(key2)
    bese64: $(base64)
